version: '3'

services:
  app1:
    build: .
    container_name: express-app1-container
    restart: always
    depends_on:
      - mysql
    ports:
      - 3000:3000

  mysql:
    platform: linux/arm64/v8
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: ClubWindDB
      MYSQL_USER: cwADMIN
      MYSQL_PASSWORD: ClubWind123
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      # Where our data will be persisted
      - my-db:/var/lib/mysql
    healthcheck:
      test: "exit 0"

# Names our volume
volumes:
  my-db:
