version: '3'

services:

  app1:
    build: .
    container_name: express-app1-container
    restart: always
    depends_on:
      - mysql
    environment:
      - PORT=3000
      - DB_HOST=mysql
      - DB_USER=cwADMIN
      - DB_PASSWORD=ClubWind123
      - DB_NAME=ClubWindDB

  app2:
    build: .
    container_name: express-app2-container
    restart: always
    depends_on:
      - mysql
    environment:
      - PORT=3001
      - DB_HOST=mysql
      - DB_USER=cwADMIN
      - DB_PASSWORD=ClubWind123
      - DB_NAME=ClubWindDB

  nginx:
    image: nginx:1.25
    container_name: ReverseProxy-Loadbalancer-container
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /data/nginx/cache
    depends_on:
      - app1
      - app2

  mysql:
    platform: linux/arm64/v8
    image: mysql
    restart: always
    environment:
      - DB_HOST=mysql
      - DB_USER=cwADMIN
      - DB_PASSWORD=ClubWind123
      - DB_NAME=ClubWindDB
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql

# Names our volume
volumes:
  my-db: