version: '3'

services:

  app1:
    build: .
    container_name: express-app1-container
    restart: always
    env_file: .env
    environment:
      - PORT=3000
      - DB_HOST=clubwinddb.mysql.database.azure.com
      - DB_USER=cwADMIN
      - DB_PASSWORD=ClubWind123
      - DB_NAME=clubwinddb

  app2:
    build: .
    container_name: express-app2-container
    restart: always
    env_file: .env
    environment:
      - PORT=3001
      - DB_HOST=clubwinddb.mysql.database.azure.com
      - DB_USER=cwADMIN
      - DB_PASSWORD=ClubWind123
      - DB_NAME=clubwinddb

  nginx:
    image: nginx:stable-alpine
    container_name: ReverseProxy-Loadbalancer-container
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /data/nginx/cache
    depends_on:
      - app1
      - app2