version: '3'

services:

  api:
    build: .
    environment:
      - DB_HOST=clubwinddb.mysql.database.azure.com
      - DB_USER=cwADMIN
      - DB_PASSWORD=ClubWind123
      - DB_NAME=ClubWindDB

  app1:
    build: .
    container_name: express-app1-container
    restart: always
    environment:
      - APP_PORT=3000
    links:
      - db

  app2:
    build: .
    container_name: express-app2-container
    restart: always
    ports:
      - 3001:3000
    environment:
      - APP_PORT=3000
    links:
      - db

  db:
    image: mysql:latest
    container_name: mysql-db-container
    restart: always
    environment:
      MYSQL_DATABASE: 'ClubWindDB'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'pass'
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql

  nginx:
    image: nginx:stable-alpine
    container_name: ReverseProxy-Loadbalancer-container
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /data/nginx/cache
    depends_on:
      - app1
      - app2
