name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME}}
        password: ${{ secrets.DOCKER_PASSWORD}}

    - uses: actions/checkout@v3
    - name: Build & Push the Docker image
      run: |
        docker build . --file Dockerfile --tag paumarro/clubwind-be:latest
        docker push paumarro/clubwind-be:latest
      